### ISSUE TITLE
Removed cHash

### ISSUE THREAD

**Issue by s-diez** [aimeos/ai-typo3#14]
Hi,

In https://github.com/aimeos/ai-typo3/commit/cbfff1af20435e429c1bc4add4969eaa78c964b9 a change was introduced which always removes cHash parameters from the generated URLs. We currently use cHashes in some specific cases. Before 19.10 we could use `client.html.CLIENT.url.config.chash` to enable this. With this change this is no longer possible.

 From the commit message I would guess this was done, because Typo3 9 does not consider `setUseCacheHash`. If this is the case, shouldn't this be a bug in Typo3 9? I am not using Typo3 9 so I have no experience with this. In any case shouldn't the value for `$this->getValue( $config, 'chash', false )` be considered before executing the preg_replace?

If the proposed change is okay I can provide a pull request.

**Comment by aimeos** [comment]
TYPO3 core devs consider cHash as required in 9.5 and won't change that. But for payment handling via remote gateways redirecting back to Aimeos it's crucial to avoid "invalid chash" errors. If chash values are useful to you in some cases, it might be OK to check that setting first but please make sure that chash values are always removed if not explicitely enabled in your PR.

**Comment by s-diez** [comment]
Thanks for merging the pull request.
