### ISSUE TITLE
Is there a reason for always appending controller / action to URL?

### ISSUE THREAD

**Issue by AndreasA** [aimeos/ai-typo3#2]
From what I can see the aimeas_typo3 extension by default only defines plugins with one action and controller.

If one were to use the feature skipDefaultArguments normally the controller and action parameter are only appended, if they are necessary, not default action of plugin but as the URL is not built by using uriFor so it basically is ignored.
However, I guess it not that easy because in order to now have those parameters when linking from the list plugin to the detail plugin, the pluginName also has to be added to the link paraemters in order for them to be removed correctly.

Due to the realurl configuration it isn't that important anyway but...

**Comment by aimeos** [comment]
The URL view helper uses the uriFor() method and that configuration option could be added. Only the T3Cli implementation does not because TYPO3 is buggy and doesn't set up the environment for the scheduler correctly to get a usable uriFor() method.

**Comment by AndreasA** [comment]
As mentioned one would also need to ensure the URLs are correctly referencing the intended pluginNames, otherwise this still would not work correctly.

This is what happens if the feature is enabled in the UriBuilder:
`
    /**
     * This removes controller and/or action arguments from given controllerArguments
     * if they are equal to the default controller/action of the target plugin.
     * Note: This is only active in FE mode and if feature "skipDefaultArguments" is enabled
     *
     * @see \TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface::isFeatureEnabled()
     * @param array $controllerArguments the current controller arguments to be modified
     * @param string $extensionName target extension name
     * @param string $pluginName target plugin name
     * @return array
     */
    protected function removeDefaultControllerAndAction(array $controllerArguments, $extensionName, $pluginName)
    {
        $defaultControllerName = $this->extensionService->getDefaultControllerNameByPlugin($extensionName, $pluginName);
        if (isset($controllerArguments['action'])) {
            $defaultActionName = $this->extensionService->getDefaultActionNameByPluginAndController($extensionName, $pluginName, $controllerArguments['controller']);
            if ($controllerArguments['action'] === $defaultActionName) {
                unset($controllerArguments['action']);
            }
        }
        if ($controllerArguments['controller'] === $defaultControllerName) {
            unset($controllerArguments['controller']);
        }
        return $controllerArguments;
    }
`

and this is the check if the feature is enabled:
`
   if ($this->environmentService->isEnvironmentInFrontendMode() && $this->configurationManager->isFeatureEnabled('skipDefaultArguments')) {
            $controllerArguments = $this->removeDefaultControllerAndAction($controllerArguments, $extensionName, $pluginName);
        }
`

Regarding setup: I think TYPO3 doesn't setup any Frontend comonents in the scheduler, so therefore the URI would not create the correct values - especially without manually setting pluginName extenionName etc.

**Comment by aimeos** [comment]
`skipDefaultArguments` is part of the TS config in the 2017.x releases
