### ISSUE TITLE
Cancelling subscription buttons are broken in 2024.10

### ISSUE THREAD

**Issue by Physikbuddha** [aimeos/ai-typo3#33]
In Aimeos 2024.07 it was possible to click the `Cancel` button in the subscriptions overview plugin to stop renewing an active running subscription. This feature does not work anymore - at least out of the box without any further configuration. The cancel button is generated with an empty `href` and will only reload the subscription overview page on click.

This is caused by a changed link generation behaviour in https://github.com/aimeos/ai-typo3/commit/269272c31796b63970174b2a2fe8b994df82d1e1 where the page uid passed to the `UriBuilder` does not fall back to `$GLOBALS['TSFE']->id` anymore. (Breaking change?)

The link to the cancel button is generated by calling `$this->link('client/html/account/subscription/url');`. The sub config key `client/html/account/subscription/url/target` is not set by default, so `null` is passed into the `UriBuilder` as target page uid. Before, it would fall back to the current page, generating a valid cancellation link.

Now, I am required to explicitly configure the target page uid. This might also be the case in other frontend plugins that I am not yet aware of.

**Comment by aimeos** [comment]
The TYPO3 core maintainers discourage using `$GLOBALS['TSFE']` as they want to remove all global variables in the future, so this was the reason for removing `$GLOBALS['TSFE']->id` fallback. On the other hand, editors shouldn't be forced to configure the same page in the flexform of the plugin.

We've tried now set the current page ID differently:
- https://github.com/aimeos/aimeos-typo3/commit/9565aefcd3fe7edfd7dfd4dbcbdf89a9f0998442
- https://github.com/aimeos/ai-typo3/commit/2b5d1b30ae40757d4ab2ceff767a66c72fb77a42

The changes are also available for 2024.10.x-dev. Can you check if that works?

**Comment by Physikbuddha** [comment]
Thank you, I can confirm that the issue is fixed and the subscription cancellation button is working again.
