### ISSUE TITLE
[bug][2018.4.0][Backend]Wrong URL in the shop switcher

### ISSUE THREAD

**Issue by guelzow** [aimeos/ai-typo3#7]
Hi everyone.

**When using:**
- multistore environment
- backend
- switched to the not-default-store

the site urls on the left top do not let you switch back.

**Our setup:**
TYPO3 8.7.10
TYPO3 Aimeos extension 18.4.0
PHP 7.2, 7.1 or 7.0

**What is happening in the Code:**
The template file (here: page-standard.php) tries to overwrite the fixed settings of the Aimeos\MW\View\Helper\Url\Typo3 class, without success.
--> https://github.com/aimeos/ai-typo3/blob/master/lib/custom/src/MW/View/Helper/Url/Typo3.php#L69
The second variable $params does not overwrite the fixed arguments.

**Our workaround so far:**
$params = array( $this->prefix => array_merge($arguments, $params) );
The array_merge() allows the overwriting of the fixed arguments.

Tobi

**Comment by aimeos** [comment]
Thank you for your report! Can you create a pull request with your change?

**Comment by aimeos** [comment]
Fixed by https://github.com/aimeos/ai-typo3/pull/8
